### ISSUE TITLE
bug: urlCache not work smoothly

### ISSUE THREAD

**Issue by MS0015** [duguyihou/react-native-turbo-image#355] opened 2024-09-18 12:52 UTC
### What's happening?

When I open the app and load the image using a remote URL, I want the image to cache. However, when I kill the app and reopen it, it still shows a gray box instead of the image. In the production build, it flickers with a black box.
<img width="364" alt="Screenshot 2024-09-18 at 6 15 52 PM" src="https://github.com/user-attachments/assets/a2e978f4-2a5f-4167-a151-77f2ada97581">
<img width="371" alt="Screenshot 2024-09-18 at 6 16 12 PM" src="https://github.com/user-attachments/assets/3ece4c93-ee2d-402d-aa56-ee2764bf0f34">

### Reproduceable Code

```tsx
<TurboImage
          tint={COLOR.GRAY}
          style={{
            position: 'relative',
            width: 22,
            height: 22,
            marginHorizontal: 4,
            ...iconStyle,
          }}
          source={iconSource}
          resizeMode={'contain'}
        />
```

### Relevant log output

```shell
no
```

### Device

iPhone xs

### TurboImage Version

1.17.2

### Can you reproduce this issue in the TurboImage Example app?

No, I cannot reproduce the issue in the Example app

**Comment by duguyihou** [comment] 2024-09-18 21:02
Can you provide a reproducer with the urls? If you want to use `urlCache`, make sure the response of the url has `cache-control`. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by MS0015** [comment] 2024-09-19 02:19
https://lyrak.fra1.cdn.digitaloceanspaces.com/icons/add-circle.png

**Comment by duguyihou** [comment] 2024-09-19 07:53
I modified the code in SuccessScreen, but I cannot reproduce the issue. The url request is only called once. To me, I did not see flicker. Is this the correct way to reproduce it?
```ts
import { StyleSheet } from 'react-native';
import React from 'react';
import TurboImage from 'react-native-turbo-image';

const SuccessScreen = () => {
  return (
    <TurboImage
      source={{
        uri: 'https://lyrak.fra1.cdn.digitaloceanspaces.com/icons/add-circle.png',
      }}
      tint="gray"
      style={styles.image}
      resizeMode="contain"
    />
  );
};

export default SuccessScreen;

const styles = StyleSheet.create({
  image: {
    width: 300,
    height: 300,
  },
});
```

https://github.com/user-attachments/assets/3a8d7d46-7802-40b0-abc9-529858222db3

**Comment by duguyihou** [comment] 2024-09-22 09:03
@MS0015 

Can you provide a reproducer?

**Comment by duguyihou** [comment] 2024-09-27 20:57
closing it since cannot reproduce it.

**Closed by duguyihou** 2024-09-27 20:57 UTC
Labels: question, cant repro
