### ISSUE TITLE
bug: Could not build Objective-C module 'react_native_turbo_image'

### ISSUE THREAD

**Issue by kbjoshi0388** [duguyihou/react-native-turbo-image#359] opened 2024-09-26 12:41 UTC
### What's happening?

I am trying to run my project in IOS simulator but it does not compile and throws error.

### Reproduceable Code

```tsx
My project is running on react native version 0.75.2. I have added this package 'react-native-turbo-image' in package.json file and then performed yarn install. Then go to ios folder and perform pod install.

Opened the project in xcode and just compile the project and it gives error.
```

### Relevant log output

```shell
1) ../node_modules/react-native-turbo-image/ios/Extensions/String+Extensions.swift Could not build Objective-C module 'react_native_turbo_image'

2) ../ios/NukeUI.xcframework/ios-arm64/NukeUI.framework/Headers/NukeUI-Swift.h:335:2 Unsupported Swift architecture
```

### Device

iPhone 15 Pro Max (iOS 17.5)

### TurboImage Version

1.19.0

### Can you reproduce this issue in the TurboImage Example app?

No, I cannot reproduce the issue in the Example app

**Comment by duguyihou** [comment] 2024-09-26 21:38
Can you provide a reproducer? I did a quick test, no compile issue on my side.

<img width="999" alt="image" src="https://github.com/user-attachments/assets/251ff78c-5e0e-4ac5-b51f-f917deb575f8">
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/945ec161-63b6-45be-a777-36c76ebbf1a8">

**Comment by kbjoshi0388** [comment] 2024-09-27 11:42
@duguyihou here is the sample project zip file. Can you try and download the zip file and try to reproduce the issue.
Demo Project link: [https://drive.google.com/file/d/1rGJquQYE96VH3FOPR6cb436gNMMhPPaf/view?usp=sharing](https://drive.google.com/file/d/1rGJquQYE96VH3FOPR6cb436gNMMhPPaf/view?usp=sharing)

**Comment by duguyihou** [comment] 2024-09-27 12:11
@kbjoshi0388 
Can you create a public repository? Then you can just send the url here.

**Comment by duguyihou** [comment] 2024-09-30 21:45
closing it since cannot reproduce it

**Closed by duguyihou** 2024-09-30 21:45 UTC
Labels: question, cant repro

**Comment by Blendfoul** [comment] 2024-10-10 13:29
Facing the same issue on `1.20.0`, this seems to be a release mode only issue.
I'm able to run and compile the application on development mode.

When running in release mode:
`
error unsupported Swift architecture
error could not build Objective-C module 'react_native_turbo_image'
`

[https://github.com/Blendfoul/AwesomeProject](repo)

To reproduce:
`npx react-native run-ios --mode Release`

**Comment by duguyihou** [comment] 2024-10-10 21:31
@Blendfoul 
I got the same error when using iOS simulator. 
Then I tested it in a physical device.
Got this.
![image](https://github.com/user-attachments/assets/7b3f2523-0642-40b6-8ed2-ec6a164cdc68)
 I don't want to install it in my computer so I used the old way to build release. 
![image](https://github.com/user-attachments/assets/f35ec922-d360-407a-947c-ca399883ca80)
 Then it works.
![File](https://github.com/user-attachments/assets/6e79ddf5-4fc3-4534-a0dc-91710f6048c3)
```ts
    <SafeAreaView style={backgroundStyle}>
      <Image
        source={{
          uri: 'https://picsum.photos/id/57/2000',
        }}
        style={{
          width: 150,
          height: 150,
        }}
      />
    </SafeAreaView>
```
I have to change the uri due to 504 error.
![image](https://github.com/user-attachments/assets/bc42faf6-3c68-48b8-a9cd-ddd536ef749c)

Can you try it in your side?

**Comment by renyufei8023** [comment] 2024-10-12 01:22
react native@0.74.5

**Comment by duguyihou** [comment] 2024-10-12 01:38
@renyufei8023 

> react native@0.74.5

I don't understand what you mean. Can you provide a reproducer if you have issue with it?

**Comment by renyufei8023** [comment] 2024-10-12 08:43
demo:https://github.com/renyufei8023/RNTest
xcode version:xcode 16 or xcode15.4
My Mac chip is from Intel, not Apple M

**Comment by renyufei8023** [comment] 2024-10-12 08:43
<img width="1658" alt="截屏2024-10-12 13 04 19" src="https://github.com/user-attachments/assets/acf7fabb-2b16-4c80-9dac-ce0884787f6a">

**Comment by renyufei8023** [comment] 2024-10-12 08:45
only iphonesimulator,The real phone does not have this issue

**Comment by duguyihou** [comment] 2024-10-12 09:55
@renyufei8023 
I see. Unfortunately, I don't have intel Mac.  Sorry I don't have plan to fix it.

**Comment by MrFarhan** [comment] 2024-10-16 15:43
Facing same issue on my macintosh:

Xcode: 15.2
React Native: 0.74.5

![Screenshot 2024-10-16 at 8 39 56 PM](https://github.com/user-attachments/assets/32870d4c-2d9d-4000-9990-701fd0168e4d)

Since we need to sync our codebase and some of our devs are unable to use this packages, so unfortunately we have to stop using this awesome library and find a better alternative :(

**Comment by duguyihou** [comment] 2024-10-16 20:29
@MrFarhan 
> some of our devs are unable to use this packages
Does it mean the rest of devs have no this compile issue? Can you provide a reproducer?

**Comment by MrFarhan** [comment] 2024-10-17 10:17
@duguyihou I have found the root cause, and after my fix this package is working fine, i have created a pull request, if you could review and if feasible then please merge that as it passes all the test cases and lint checks.

My below PR adds the support for macintosh / intel architecture  :

https://github.com/duguyihou/react-native-turbo-image/pull/370

**Comment by duguyihou** [comment] 2024-10-17 20:21
@MrFarhan 
Thanks for the PR. Currently we have to use xcframework to integrate Nuke, so I think what's why it does not work well with iOS simulator. The PR should work.  I will do more testing and merge it if ok. My further plan is to integrate it with SPM.

**Comment by MrFarhan** [comment] 2024-10-21 10:17
@renyufei8023  @Blendfoul @kbjoshi0388 can you guys install the latest version and check if still you are facing this issue, as this issue is fixed in latest PR merge.
